import { GamesAPIResult } from "model";

export const normalizeGame = (game: GamesAPIResult) => ({
  id: game.id ?? 0,
  season: game.season ?? 0,
  seasonType: game.seasonType ?? 0,
  week: game.week ?? 0,
  startDate: game.startDate ?? '',
  awayTeam: game.awayTeam ?? '',
  homeTeam: game.homeTeam ?? '',
  awayPoints: game.awayPoints ?? 0,
  homePoints: game.homePoints ?? 0,
  pointSpread: game.pointSpread ?? 0,
  attendance: game.attendance ?? 0,
  awayTeamAPRanking: game.awayTeamAPRanking ?? 0,
  homeTeamAPRanking: game.homeTeamAPRanking ?? 0,
  awayTeamCFPRanking: game.awayTeamCFPRanking ?? 0,
  homeTeamCFPRanking: game.homeTeamCFPRanking ?? 0,
  awayTeamData: {
    ...game.awayTeamData,
    playoffRank: game.awayTeamData?.playoffRank ?? undefined,
    apRank: game.awayTeamData?.apRank ?? undefined,
    coachesRank: game.awayTeamData?.coachesRank ?? undefined
  },
  homeTeamData: {
    ...game.homeTeamData,
    playoffRank: game.homeTeamData?.playoffRank ?? undefined,
    apRank: game.homeTeamData?.apRank ?? undefined,
    coachesRank: game.homeTeamData?.coachesRank ?? undefined
  },
  notes: game.notes ?? '',
  startTimeTBD: game?.startTimeTBD ?? false,
  venueId: game?.venueId ?? 0,
  venue: game?.venue ?? '',
  outcomes: game.outcomes ?? undefined,
  neutralSite: game.neutralSite ?? false,
  conferenceGame: game.conferenceGame ?? false,
  homeId: game.homeId ?? 0,
  homeConference: game.homeConference ?? '',
  homeLineScores: game.homeLineScores ?? [],
  homePostgameWinProbability: game.homePostgameWinProbability ?? 0,
  homePregameElo: game.homePregameElo ?? 0,
  homePostgameElo: game.homePostgameElo ?? 0,
  awayId: game.awayId ?? 0,
  awayConference: game.awayConference ?? '',
  awayLineScores: game.awayLineScores ?? [],
  awayPostgameWinProbability: game.awayPostgameWinProbability ?? 0,
  awayPregameElo: game.awayPregameElo ?? 0,
  awayPostgameElo: game.awayPostgameElo ?? 0,
  excitementIndex: game.excitementIndex ?? 0,
  highlights: game.highlights ?? '',
  completed: game.completed ?? false,
  homeClassification: game.homeClassification ?? null,
  awayClassification: game.awayClassification ?? null,

})